# Generated by Django 4.0.4 on 2022-05-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fechaDeDevolucion',
        ),
    ]
